### ISSUE TITLE
As a user, I want to be able to login if necessary so that I can save and view my past results

### ISSUE THREAD

**Issue by ghost** [mashalm/JD1_frontend#1]

**Comment by mashalm** [comment]
- Story / Task Details:
  - Research backend platforms (parse, firebase) vs custom code for next sprint
  - Create database necessary for storing users, credentials, and test results

- Acceptance criteria: Allow users to sign up, log in, store, and retrieve their results.

- Done Criteria: Database is secured by an authentication system; code is merged into master; code is covered by unit tests.
